### ISSUE TITLE
Check the version of Node installed on the laptop of the developer

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/project-starter#29]
We can add add a rule to check the version of Node installed on the machine of the developper. If this rule failed, we will do nothing, except logging a warning message to the developer

If we use this releases diagram, https://nodejs.org/en/about/releases/, we can log a warning if the version of the used NodeJS is less or equal Node 6. 

In order to get this information, we can use maybe the module `check-node-version` https://www.npmjs.com/package/check-node-version

**Comment by ig1na** [comment]
We could check this dynamically on this json file https://github.com/nodejs/Release/blob/master/schedule.json so we always have the latest information on node version deprecation
