### ISSUE TITLE
Create flags for listing rules to apply and force applies

### ISSUE THREAD

**Issue by ig1na** [DX-DeveloperExperience/project-starter#59]
User should be able to show an audit with every explanation of what a rule will do, and also should be able to apply every rules or selected rules with a single flag

**Comment by EmmanuelDemey** [comment]
We should add 

- an `dry-run` flag to our command line, that will display all the rules for which something has to be done (rule with the `shouldBeApplied` method returning `true`

- a `apply` flag that will apply all rules without the confirmation of the user

- a `manual` flag that will display the prompt to the user all choices he can do (the behavior today). 

The default behavior will be the `dry-run`
