### ISSUE TITLE
Be able to say manually if rule has to be applied or not

### ISSUE THREAD

**Issue by EmmanuelDemey** [DX-DeveloperExperience/project-starter#90]
Should give the possibility for some rules to be applied or not manually. 

For example, if we know that a specific rule can not be verified by our program, we can let the user say yes or no this rule has to be applied. 

If the user say yes, the `apply` method of the rule will be called.

**Comment by ig1na** [comment]
To do this, the developper may add an inquirer prompt inside the shouldBeAppliedFunction, one example is in the integration-tests rules of elasticsearch rules.
